Vagrant.configure("2") do |config|
  ## Global setting ...
  ## This line enables the Hostmanager plugin ##
  ## Vagrant will automatically manage host file entries on both the host machine and the guest VM ##
  config.hostmanager.enabled = true 

  ## Global setting 
  ## This line specifies that Vagrant should manage the host file on the host machine ##
  ## Vagrant will update the host file on the host machine to include entries- 
  ## for the IP addresses of the guest VMs ##
  config.hostmanager.manage_host = true
  
### DB vm  ####
  # Define a virtual machine named "db01"
  config.vm.define "db01" do |db01|
    # Set the base box for the VM to "eurolinux-vagrant/centos-stream-9"
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    # Set the hostname of the VM to "db01"
    db01.vm.hostname = "db01"
    # Configure a private network with a static IP address of "192.168.56.15" for the VM
    db01.vm.network "private_network", ip: "192.168.56.15"
    # Configure provider-specific settings for VirtualBox
    db01.vm.provider "virtualbox" do |vb|
      # Set the memory (RAM) allocation for the VM to "600" MB
     vb.memory = "600"
   end
   
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
  rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    rmq01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "800"
   end
   end
   
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
  web01.vm.network "private_network", ip: "192.168.56.11"
  web01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "800"
   end
end
  
end
